# Generated by Django 4.2.4 on 2023-08-08 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('speed', models.IntegerField()),
                ('size', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('char_class', models.CharField()),
                ('level', models.IntegerField()),
                ('alignment', models.CharField()),
                ('background', models.CharField()),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters_feature', to='char_app.feature')),
                ('languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters_language', to='char_app.language')),
                ('proficiencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters_proficiency', to='char_app.proficiency')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters_skill', to='char_app.skill')),
                ('spells', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters_spell', to='char_app.spell')),
                ('traits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters_trait', to='char_app.trait')),
            ],
        ),
    ]
