# Generated by Django 4.2.4 on 2023-08-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0003_alter_skill_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
