# Generated by Django 4.2.4 on 2023-08-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0005_rename_char_class_character_charclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='chaSaving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='conSaving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='dexSaving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='intSaving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='strSaving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='wisSaving',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
