# Generated by Django 4.2.4 on 2023-08-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0006_character_chasaving_character_consaving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='currentHitPoints',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='deathFailure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='deathSuccess',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='hitDice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='tempHitPoints',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
