# Generated by Django 4.2.4 on 2023-08-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0007_character_currenthitpoints_character_deathfailure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bonds',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='flaws',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='ideals',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='personalityTraits',
            field=models.CharField(blank=True, null=True),
        ),
    ]
