# Generated by Django 4.2.4 on 2023-08-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0008_character_bonds_character_flaws_character_ideals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='otherProficiencies',
            field=models.CharField(blank=True, null=True),
        ),
    ]
