# Generated by Django 4.2.4 on 2023-08-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0011_character_eyes_character_hair_character_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='speed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
