# Generated by Django 4.2.4 on 2023-08-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0014_character_initiative'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
