# Generated by Django 4.2.4 on 2023-08-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0015_character_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='sex',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
